apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mathtrail-infra-observability

manifests:
  rawYaml:
    - manifests/dapr-configuration.yaml
    - manifests/network-policies.yaml

deploy:
  kubectl:
    defaultNamespace: ${NAMESPACE}

  helm:
    flags:
      install: ["--timeout", "10m"]
      upgrade: ["--timeout", "10m"]
    releases:
      # 1. Deploy LGTM stack first (foundation with Alloy receiver)
      - name: lgtm
        repo: ${CHARTS_REPO}
        remoteChart: k8s-monitoring
        version: 3.8.0
        namespace: monitoring
        createNamespace: false
        wait: true
        valuesFiles:
          - values/lgtm-values.yaml

      # 2. Deploy Pyroscope (independent)
      - name: pyroscope
        repo: ${CHARTS_REPO}
        remoteChart: pyroscope
        version: 1.18.1
        namespace: monitoring
        createNamespace: false
        wait: true
        valuesFiles:
          - values/pyroscope-values.yaml

      # 3. Deploy OTel Collector last (depends on Alloy being ready)
      - name: otel-collector
        repo: ${CHARTS_REPO}
        remoteChart: opentelemetry-collector
        version: 0.145.0
        namespace: monitoring
        createNamespace: false
        wait: true
        valuesFiles:
          - values/otel-collector-values.yaml

# Port forwarding for local access
portForward:
  - resourceType: service
    resourceName: lgtm-grafana
    namespace: monitoring
    port: 80
    localPort: 3000

  - resourceType: service
    resourceName: pyroscope
    namespace: monitoring
    port: 4040
    localPort: 4040

  - resourceType: service
    resourceName: otel-collector-opentelemetry-collector
    namespace: monitoring
    port: 9411
    localPort: 9411
