apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-base

deploy:
  helm:
    releases:
      # Namespace, network policies
      - name: infra-base
        chartPath: manifests/
        wait: true
        setValueTemplates:
          namespace: "{{.NAMESPACE}}"
          monitoringNamespace: "{{.MONITORING_NAMESPACE}}"

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mathtrail-infra-observability
requires:
  - configs: [infra-base]

deploy:
  helm:
    flags:
      install: ["--timeout", "10m"]
      upgrade: ["--timeout", "10m"]
    releases:
      # 1. Loki — log storage
      - name: loki
        repo: "{{.CHARTS_REPO}}"
        remoteChart: loki
        version: 6.53.0
        namespace: "{{.MONITORING_NAMESPACE}}"
        createNamespace: false
        wait: true
        valuesFiles:
          - values/loki-values.yaml

      # 2. Tempo — trace storage
      - name: tempo
        repo: "{{.CHARTS_REPO}}"
        remoteChart: tempo
        version: 1.24.4
        namespace: "{{.MONITORING_NAMESPACE}}"
        createNamespace: false
        wait: true
        valuesFiles:
          - values/tempo-values.yaml

      # 3. Mimir — metrics storage
      - name: mimir
        repo: "{{.CHARTS_REPO}}"
        remoteChart: mimir-distributed
        version: 6.0.5
        namespace: "{{.MONITORING_NAMESPACE}}"
        createNamespace: false
        wait: true
        valuesFiles:
          - values/mimir-values.yaml

      # 4. Grafana — observability UI
      - name: grafana
        repo: "{{.CHARTS_REPO}}"
        remoteChart: grafana
        version: 10.5.15
        namespace: "{{.MONITORING_NAMESPACE}}"
        createNamespace: false
        wait: true
        valuesFiles:
          - values/grafana-values.yaml

      # 5. Alloy collectors (k8s-monitoring) — ships data to backends
      - name: alloy
        repo: "{{.CHARTS_REPO}}"
        remoteChart: k8s-monitoring
        version: 3.8.0
        namespace: "{{.MONITORING_NAMESPACE}}"
        createNamespace: false
        wait: true
        valuesFiles:
          - values/alloy-values.yaml

      # 6. Pyroscope — continuous profiling
      - name: pyroscope
        repo: "{{.CHARTS_REPO}}"
        remoteChart: pyroscope
        version: 1.18.1
        namespace: "{{.MONITORING_NAMESPACE}}"
        createNamespace: false
        wait: true
        valuesFiles:
          - values/pyroscope-values.yaml

      # 7. OTel Collector — receives from services, sends to Alloy
      - name: otel-collector
        repo: "{{.CHARTS_REPO}}"
        remoteChart: opentelemetry-collector
        version: 0.145.0
        namespace: "{{.MONITORING_NAMESPACE}}"
        createNamespace: false
        wait: true
        valuesFiles:
          - values/otel-collector-values.yaml
        setValueTemplates:
          config.exporters.otlp/alloy.endpoint: "lgtm-alloy-receiver.{{.MONITORING_NAMESPACE}}.svc.cluster.local:4317"

# Port forwarding for local access
portForward:
  - resourceType: service
    resourceName: lgtm-grafana
    namespace: "{{.MONITORING_NAMESPACE}}"
    port: 80
    localPort: 3000

  - resourceType: service
    resourceName: pyroscope
    namespace: "{{.MONITORING_NAMESPACE}}"
    port: 4040
    localPort: 4040

  - resourceType: service
    resourceName: otel-collector-opentelemetry-collector
    namespace: "{{.MONITORING_NAMESPACE}}"
    port: 9411
    localPort: 9411
