apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: infra-base

deploy:
  helm:
    releases:
      # Namespace, network policies, Dapr config
      - name: infra-base
        chartPath: manifests/
        wait: true
        setValueTemplates:
          namespace: "{{.NAMESPACE}}"
          monitoringNamespace: "{{.MONITORING_NAMESPACE}}"

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mathtrail-infra-observability
requires:
  - configs: [infra-base]

deploy:
  helm:
    flags:
      install: ["--timeout", "10m"]
      upgrade: ["--timeout", "10m"]
    releases:
      # 1. Deploy LGTM stack (foundation with Alloy receiver)
      - name: lgtm
        repo: "{{.CHARTS_REPO}}"
        remoteChart: k8s-monitoring
        version: 3.8.0
        namespace: "{{.MONITORING_NAMESPACE}}"
        createNamespace: false
        wait: true
        valuesFiles:
          - values/lgtm-values.yaml

      # 2. Deploy Pyroscope (independent)
      - name: pyroscope
        repo: "{{.CHARTS_REPO}}"
        remoteChart: pyroscope
        version: 1.18.1
        namespace: "{{.MONITORING_NAMESPACE}}"
        createNamespace: false
        wait: true
        valuesFiles:
          - values/pyroscope-values.yaml

      # 3. Deploy OTel Collector last (depends on Alloy being ready)
      - name: otel-collector
        repo: "{{.CHARTS_REPO}}"
        remoteChart: opentelemetry-collector
        version: 0.145.0
        namespace: "{{.MONITORING_NAMESPACE}}"
        createNamespace: false
        wait: true
        valuesFiles:
          - values/otel-collector-values.yaml
        setValueTemplates:
          config.exporters.otlp/alloy.endpoint: "lgtm-alloy-receiver.{{.MONITORING_NAMESPACE}}.svc.cluster.local:4317"

# Port forwarding for local access
portForward:
  - resourceType: service
    resourceName: lgtm-grafana
    namespace: "{{.MONITORING_NAMESPACE}}"
    port: 80
    localPort: 3000

  - resourceType: service
    resourceName: pyroscope
    namespace: "{{.MONITORING_NAMESPACE}}"
    port: 4040
    localPort: 4040

  - resourceType: service
    resourceName: otel-collector-opentelemetry-collector
    namespace: "{{.MONITORING_NAMESPACE}}"
    port: 9411
    localPort: 9411
